version: "3.0"
services:
    app:
        build: .
        volumes:
            - ./src:/app
        tty: true
        restart: always
        environment:
            PYTHONIOENCODING: utf-8
